name: APML
channels:
  - conda-forge
  - nodefaults
dependencies:
  - tensorflow-gpu=2.12
  - numba
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - xarray
  - pip
  - pip:
    - deepsmiles
    - rdkit