name: APML
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numba
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - xarray
  - pip
  - pip:
    - tensorflow[and-cuda]==2.12
    - deepsmiles
    - rdkit